### ISSUE TITLE
npm i unable to run in backend becuase of there is NO package.json file not available

### ISSUE THREAD

**Issue by shankermjj** [denizumutdereli/smart-contract-langchain-advisor#2]
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\kmit\Smart_LLM\smart-contract-langchain-advisor\python\backend/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\kmit\Smart_LLM\smart-contract-langchain-advisor\python\backend\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kmit\AppData\Local\npm-cache\_logs\2024-07-27T11_08_08_830Z-debug-0.log

**Comment by denizumutdereli** [comment]
They are under client and server folders. You should run inside of them.

**Comment by denizumutdereli** [comment]
if any further problem happens, please write to me. Thanks.

**Comment by shankermjj** [comment]
> if any further problem happens, please write to me. Thanks.

Please can you share your Mail Id please. Already i given Request in Lnkedin.
Your Project was Excellent.

**Comment by denizumutdereli** [comment]
I think you are mixed with nodejs and python
python\backend/ -> this python flask api  and langchain is running on

the package.json files are under reactui / the folders server / client .

so I mean you should run 3 of them at the same time.

reactui/client is the UI (this is nodejs)

reactui/server is for the proxy between flask api and react component (this is nodejs)

python/backend is with py - and the actual langchain code is running (this is python - so there is no need package.json here)

**Comment by shankermjj** [comment]
Unable to Register

![image](https://github.com/user-attachments/assets/746a930b-ae50-4f34-89ab-f8334c0777c3)

**Comment by denizumutdereli** [comment]
you should compose up the database containers.
